# Generated by Django 4.2.6 on 2023-10-14 12:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_medicationsrecord_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memories',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 14, 18, 23, 20, 38406)),
        ),
    ]
