# Generated by Django 4.2.6 on 2023-10-14 20:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_memories_date_posted_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memories',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 15, 2, 14, 7, 761453)),
        ),
    ]
